# Generated by Django 5.0 on 2023-12-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('username', models.CharField(max_length=60, unique=True)),
                ('question', models.CharField(choices=[('What was the name of your first pet?', 'What was the name of your first pet?'), ('In which city or town were you born?', 'In which city or town were you born?'), ('What is the title of your favorite book or movie?', 'What is the title of your favorite book or movie?'), ('What is the name of the city where you attended your first concert?', 'What is the name of the city where you attended your first concert?'), ('Who is your favorite author or film director?', 'Who is your favorite author or film director?')])),
                ('answer', models.CharField(max_length=128)),
                ('income', models.FloatField()),
                ('expense', models.FloatField(default=0)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_text', models.CharField(max_length=50)),
                ('amount', models.FloatField(null=True)),
                ('expense_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensetracker.expenseprofile')),
            ],
        ),
    ]
