# Generated by Django 5.0 on 2023-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bookkeypoint',
            name='point',
            field=models.CharField(max_length=200),
        ),
    ]
