# Generated by Django 4.2.7 on 2023-11-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='portfolio/thumbnails/'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projectcategory'),
        ),
    ]
