"""
Django settings for jawaddev project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o7841qcq$mrf$x73=0l)wtzjd9ny+&8k+-gf1cna)@$31gu4q&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'anymail',
    'ckeditor',
    'widget_tweaks',
    "phonenumber_field",
    'user.apps.UserConfig',
    'core.apps.CoreConfig',
    'home.apps.HomeConfig',
    'blog.apps.BlogConfig',
    'portfolio.apps.PortfolioConfig',
]

# CKEditor

CKEDITOR_CONFIGS = {
    'default': {
        'extraPlugins': 'codesnippet',
        'codeSnippet_theme': 'monokai_sublime',
    },
}

# ANYMAIL

ANYMAIL = {
    "MAILGUN_API_KEY": 'c3f588a1fc56bcd2fad94118efecf4a5-1c7e8847-dc3c044b',
    "MAILGUN_SENDER_DOMAIN": 'sandbox0ef92156ea3048199e1e35addaea559a.mailgun.org',
}
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend" 
DEFAULT_FROM_EMAIL = 'jawad4world@gmail.com'  
SERVER_EMAIL = 'jawad4world@gmail.com'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jawaddev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.profile'
            ],
        },
    },
]

WSGI_APPLICATION = 'jawaddev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': '22gGEEEe-fAf24cDGedABf1dcaBc1fGa',
        'HOST': 'monorail.proxy.rlwy.net',
        'PORT': '44125',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

LOGIN_REDIRECT_URL = 'user:profile'
LOGOUT_REDIRECT_URL = 'home'

MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = 'media/'

STATIC_ROOT = BASE_DIR / 'static'

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# USERNAME: me
# PASSWORD: Y#SthisisM3

# profile:

# USERNAME: Jawad
# FIRST NAME: M. Jawad
# LAST NAME: Bacha
# EMAIL: jawad4world@gmail.com
# PASSWORD: j@W@dATH!ZP0RTF0LI0

