# Generated by Django 4.2.7 on 2023-12-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookkeypoint',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookKeyPoint',
        ),
    ]
