# Generated by Django 4.2.7 on 2023-11-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_categories_alter_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projectcategory'),
        ),
    ]
