# Generated by Django 5.0 on 2023-12-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_project_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('sub_title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=60)),
                ('web_name', models.CharField(max_length=60)),
                ('web_url', models.URLField()),
                ('github_url', models.URLField()),
                ('introduction', models.TextField()),
                ('Objectives', models.TextField()),
                ('approach', models.TextField()),
                ('evaluation', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('frameworks', models.ManyToManyField(to='portfolio.reviewframework')),
                ('infrastructures', models.ManyToManyField(to='portfolio.reviewinfrastructure')),
                ('languages', models.ManyToManyField(to='portfolio.reviewlanguage')),
                ('packages', models.ManyToManyField(to='portfolio.reviewpackage')),
                ('softwares', models.ManyToManyField(to='portfolio.reviewsoftware')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('project_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projectreview')),
            ],
        ),
    ]
