# Generated by Django 5.0 on 2023-12-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_reviewframework_reviewinfrastructure_reviewlanguage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewFeatures',
            new_name='ReviewFeature',
        ),
    ]
