# Generated by Django 5.0 on 2023-12-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_reviewfeatures_reviewfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
