# Generated by Django 4.2.7 on 2023-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(editable=False, max_length=60, null=True, unique=True),
        ),
    ]
